apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "hello-world-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world-app.selectorLabels" . | nindent 8 }}
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
              name: http
          env:
            - name: APP_VERSION
              value: {{ .Values.deployment.env.appVersion | quote }}
            - name: PORT
              value: {{ .Values.deployment.env.port | quote }}
            - name: DEBUG
              value: {{ .Values.deployment.env.debug | quote }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
