apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-app.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}
    name: {{ .Values.service.name }}
  selector:
    {{- include "hello-world-app.selectorLabels" . | nindent 4 }}
