apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Refresh automático mais frequente (padrão é 180s)
  timeout.reconciliation: "30s"
  # Timeout para operações Git
  timeout.git-request: "30s"