replicaCount: 3

image:
  repository: robarros/argocd-app
  tag: "224a535"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

namespace:
  name: hello-world
  create: true
  labels:
    name: hello-world
    app.kubernetes.io/managed-by: argocd

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  protocol: TCP
  name: http

deployment:
  labels:
    app: hello-world-app
    version: v1
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  containerPort: 5000
  
  env:
    appVersion: "1.0.0"
    port: "5000"
    debug: "false"
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
