apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: httpd
  labels:
    app: httpd
    version: v1
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: httpd
    version: v1