name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: robarros/argocd-app
  REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: |
        cd app
        # Testar se a aplicação inicia sem erros
        timeout 10s python app.py || true

    - name: Generate version tags
      id: meta
      run: |
        # Gerar tags baseadas no commit
        COMMIT_SHA=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        
        # Tags que serão criadas
        TAGS="${DOCKER_IMAGE}:${COMMIT_SHA}"
        TAGS="${TAGS},${DOCKER_IMAGE}:${TIMESTAMP}"
        TAGS="${TAGS},${DOCKER_IMAGE}:latest"
        
        # Se for branch main, adicionar tag stable
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAGS="${TAGS},${DOCKER_IMAGE}:stable"
        fi
        
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        echo "version=${COMMIT_SHA}" >> $GITHUB_OUTPUT
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          APP_VERSION=${{ steps.meta.outputs.version }}

    - name: Update Kubernetes deployment
      run: |
        # Atualizar a imagem no deployment do Kubernetes
        sed -i "s|image: hello-world-app:latest|image: ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}|g" k8s/hello-world-app/deployment.yaml
        
        # Adicionar annotation para forçar rollout
        sed -i "/template:/a\\        annotations:\\n          deployment.kubernetes.io/revision: \"${{ steps.meta.outputs.timestamp }}\"" k8s/hello-world-app/deployment.yaml

    - name: Commit and push changes
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Verificar se há mudanças
        if git diff --quiet k8s/hello-world-app/deployment.yaml; then
          echo "Nenhuma mudança no deployment"
        else
          git add k8s/hello-world-app/deployment.yaml
          git commit -m "🚀 Update deployment image to ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }} [skip ci]"
          git push
        fi

    - name: Create deployment summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Item | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| **Docker Image** | \`${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| **Commit SHA** | \`${{ steps.meta.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| **Timestamp** | \`${{ steps.meta.outputs.timestamp }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| **Branch** | \`${{ github.ref_name }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Docker Tags Created:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🎯 Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. ArgoCD will automatically detect the changes and sync the application" >> $GITHUB_STEP_SUMMARY
        echo "2. Monitor the deployment in your ArgoCD dashboard" >> $GITHUB_STEP_SUMMARY
        echo "3. Verify the application is running with the new image" >> $GITHUB_STEP_SUMMARY

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKER_IMAGE }}:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'